### ISSUE TITLE
Mouse doesn't work. Trackball support

### ISSUE THREAD

**Issue by Biryuk666** [blueminder/flycast-dojo#14]
Hello! Mouse does not work when playing in OUTTRIGGER (naomi version). Mouse buttons are functioning, but mouse movement is not logged. There may be no trackball support. And please add the vertical axis inversion of the mouse to the settings.
Thank you!

**Comment by blueminder** [comment]
You might want to report this to [flyinghead/flycast](https://github.com/flyinghead/flycast/) instead of here. This fork deals with netplay/replay specific functions and inherits everything upstream from there.
