### ISSUE TITLE
Command Line Netplay crashes

### ISSUE THREAD

**Issue by smb1982** [blueminder/flycast-dojo#15]
Platform / OS / Hardware: Windows 10 x64

Hardware: 10 Gen Intel, w/ Geforce 1660

**_Description of the Issue_**

Using the commands listed in the Readme, ie./

flycast.exe -config dojo:Enable=yes -config dojo:EnableMatchCode=no -config dojo:ActAsServer=yes -config dojo:ServerPort=6000 -config dojo:PlayerName=Player1 roms\capsnk.zip

flycast.exe -config dojo:Enable=yes -config dojo:EnableMatchCode=no -config dojo:ActAsServer=no -config dojo:ServerIP=10.1.1.30 -config dojo:ServerPort=6000 -config dojo:PlayerName=Player2 roms\capsnk.zip

They connect but as soon as you press Start Session, both crash (if using commandline from above).  

Works and plays great setting up a match using the GUI...

**_Debugging Steps Tested_**

 Tried both ActAsServer, either, tried different ports etc.

**_Logs Gathered_**

```

Can't get anything useful from Flycast.exe

**Comment by blueminder** [comment]
It looks like what I have in the docs is out of date. I just updated the README to reflect this.

Try the following instead:

Host:
```
./flycast.exe -config network:GGPO=yes -config dojo:EnableMatchCode=no -config network:ActAsServer=yes -config network:server=127.0.0.1 -config network:GGPOPort=6000 -config network:GGPORemotePort=6001 ROMs\capsnk.zip
```

Guest:
```
 ./flycast.exe -config network:GGPO=yes -config dojo:EnableMatchCode=no -config network:ActAsServer=no -config network:server=127.0.0.1 -config network:GGPOPort=6001 -config network:GGPORemotePort=6000 ROMs\capsnk.zip
```
