### ISSUE TITLE
Games dont show

### ISSUE THREAD

**Issue by juanroman74454811** [blueminder/flycast-dojo#16]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: 

Hardware: idk

**_Description of the Issue_**

Im trying to put Chu Chu Rocket! but the rom wont appear

**Comment by blueminder** [comment]
I'm going to need more information than this. What's the filename? Is it in the provided `ROMs` folder or did you add a directory to "Content Location" in your General settings?

**Comment by juanroman74454811** [comment]
> I'm going to need more information than this. What's the filename? Is it in the provided `ROMs` folder or did you add a directory to "Content Location" in your General settings?

File name: Chu chu rocket.zip

**Comment by blueminder** [comment]
Flycast supports CHD, GDI, CUE, and CDI. If you have a ZIP files, you should unzip it first.

**Comment by juanroman74454811** [comment]
> Flycast supports CHD, GDI, CUE, and CDI. If you have a ZIP file, you should unzip it first.

Oh shi-
