### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by man-of-eel** [blueminder/flycast-dojo#17]
The README states:
> To compile on your own, just head to `shell/linux` and run `make -j8`

But there is no Makefile there.

**Comment by blueminder** [comment]
Those instructions are out of date. It now uses CMake. You can take a look at [.github/workflows/c-cpp.yml](https://github.com/blueminder/flycast-dojo/blob/master/.github/workflows/c-cpp.yml) to see how GitHub Actions compiles it.
