### ISSUE TITLE
Some games have map error with some grahics API

### ISSUE THREAD

**Issue by leoxxx** [blueminder/flycast-dojo#19]
OS:WIN7 X64 
CPU:I5 3470 
GPU:7850 1G

DYNAMITE DEKA EX
VULKAN
![Snap3](https://user-images.githubusercontent.com/5364709/161297277-bd997216-3e87-4682-b9cc-dc8716fba677.png)
Ohters APIs have a little error, but can play.

THE KING OF FIGHTERS NEO WAVE
DIRECTX11
![Snap1](https://user-images.githubusercontent.com/5364709/161297489-fb459bc4-ad26-49f4-aa3f-a40adfe8d0fc.png)
![Snap2](https://user-images.githubusercontent.com/5364709/161297515-4b4b2fdc-98a9-4f71-a835-41932f1ddf20.png)
 
It's fine with dx11 in demul.

NEOGEO BATTLE COLISEUM
VULKAN
![Snap3](https://user-images.githubusercontent.com/5364709/161373816-1d0a40c4-edb6-4001-aac5-e9bf5cf0e206.png)

All API
![Snap1](https://user-images.githubusercontent.com/5364709/161373850-15b0c818-9b73-4cd3-b097-fc9116a454fc.png)
![Snap2](https://user-images.githubusercontent.com/5364709/161373861-d7cf11d5-1450-4bd2-9e87-7504b750c090.png)

It's fine with dx11 in demul.

**Comment by blueminder** [comment]
Please bring this up to the upstream project. Flycast Dojo does not deal with graphics API changes:
https://github.com/flyinghead/flycast
