### ISSUE TITLE
KenJu Dreamcast port booting to empty SEGA screen

### ISSUE THREAD

**Issue by nedstool** [blueminder/flycast-dojo#2]
Title, the ROM is in the correct place and so are the BIOs files, and I've tried various different BIOs files aswell so it's not that.

![image](https://user-images.githubusercontent.com/54012679/108306795-8b2b1900-7172-11eb-9efa-13488fed3fda.png)

**Comment by blueminder** [comment]
Game emulation issues should be sent to the main Flycast repository here: https://github.com/flyinghead/flycast
