### ISSUE TITLE
error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory on Manjaro Linux

### ISSUE THREAD

**Issue by magomagal** [blueminder/flycast-dojo#21]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: **PC/ Manjaro Linux/ kernel Linux 5.15.28-1 LTS/ Nvidia GTX 1650m, i5 9th gen**

Github hash: 

Hardware: 

**_Description of the Issue_**

I always get this error while trying to run flycast.elf: "error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory"

**_Debugging Steps Tested_**

  * I already tried reinstalling all of the dependencies but to no avail.
**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blueminder** [comment]
Please install the dependencies shown in the README. Lua is included there: https://github.com/blueminder/flycast-dojo#linux-build

If you still get the same error, try making a symbolic link to the installed liblua location:
`ln -s /app/lib/liblua.so /app/lib/liblua5.3.so.0`
