### ISSUE TITLE
Fatal: Unhandled SH4 exception when loading save state in South Park Rally (USA)

### ISSUE THREAD

**Issue by Shideravan** [blueminder/flycast-dojo#29]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10 x64
Intel 4790
GTX 1070
16 RAM DDR3

Github hash: flycast-dojo-0.4.57

**_Description of the Issue_**
I created a savestate with Flycast-dojo, but when loading it (both in dojo and in vallina version) I get "Fatal: Unhandled SH4 exception" which crashes the game. The game tested is South Park Rally (USA) in CHD format.
I'm including the savestate attached with this issue.
[South Park Rally (US).zip](https://github.com/blueminder/flycast-dojo/files/9479554/South.Park.Rally.US.zip)

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```
Leaving blank as I didn't make any log yet.

**_Screenshots_**

![image](https://user-images.githubusercontent.com/12163923/188194540-6d06ccff-7809-4876-963b-2f1e3a2b8001.png)

**Comment by blueminder** [comment]
If this affects both Dojo & vanilla, it is best to make a ticket in the upstream repository https://github.com/flyinghead/flycast/ . Dojo incorporates updates from there.
