### ISSUE TITLE
Flycast dojo-0.4.7 crashing upon game load - AMD ryzen r7 1700x 1st gen, windows 10

### ISSUE THREAD

**Issue by DiegoAlexanderManjarres** [blueminder/flycast-dojo#3]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10

Hardware: 
cpu AMD ryzen 1st gen 1700x
Nvidia gtx 1080

**_Description of the Issue_**

Hi, just havig issues with latest build of flycast dojo 0.4.7 crashin upon game load. This is not the case when going back to  flycast exe 0.4.4.1, it  works without any issue, however 
Fightcade wants the version 0.4.7

**_Debugging Steps Tested_**
Deleted all the appdata fightcade content and reinstaled fightcade with no success. Just going back to build 0.4.4.1 had the games loading without crashing.

**_Logs Gathered_**
00:00:000 hw/mem/_vmem.cpp:499 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:024 hw/mem/_vmem.cpp:499 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:055 hw/naomi/naomi_cart.cpp:186 W[NAOMI]: Warning: Region 1 bios not found in awbios
00:00:734 hw/naomi/naomi_cart.cpp:366 N[NAOMI]: NAOMI GAME ID [THE KING OF FIGHTERS XI]
00:00:734 ./nullDC.cpp:234 N[BOOT]: Game ID is [THE KING OF FIGHTERS XI]
00:00:734 hw/naomi/naomi_cart.cpp:186 W[NAOMI]: Warning: Region 1 bios not found in awbios
00:00:831 windows/winmain.cpp:199 E[COMMON]: [GPF] PC 00007ff75f4d4440 unhandled access to 00000000000001a0
```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blueminder** [comment]
Thanks for filing this report. I'm going to work on replicating this bug.

Since the main feature addition in 0.4.7 is individual controller profiles for Dreamcast and Arcade, can you try remapping your controls and seeing if that works? I'm currently working on making a clean fallback for those using old mappings.

**Comment by DiegoAlexanderManjarres** [comment]
Thanks for the quick replay, so I went a head and remap my ds4 controller, and  Flycast is working now. Thanks a lot, never would have thought of that one.

**Comment by blueminder** [comment]
No problem. I already have a fix ready to fall back to the old mapping format when a new profile isn't found. It should be included in 0.4.8. Thanks again for the report!

**Comment by sharicov** [comment]
having microfreezes and crash
flycast-dojo-0.4.57
amd processor
amd graphics

**Comment by blueminder** [comment]
@sharicov Did you try following these steps?

http://flycast.dojo.ooo/faq.html#crash
