### ISSUE TITLE
high CPU waste in 0.5.1 while idle

### ISSUE THREAD

**Issue by WAZAAAAA0** [blueminder/flycast-dojo#30]
0.5.1 consumes a lot of CPU for no apparent reason while doing absolutely nothing. Issue reproduced by at least 3 people, on Win10 and Win7. Steps to reproduce: 
1. download and extract flycast-dojo-0.5.1.zip (vanilla settings)
2. run Flycast.exe, don't do anything
3. observe the CPU with Task Manager, and compare it to the previous version
```
0.4.57 =  2% CPU | 1.80% GPU
0.5.1  = 25% CPU | 1.70% GPU
```
further inspection with Process Hacker shows the culprit being a thread called `msvcrt.dll!beginthreadex+0xd4`

**Comment by leoxxx** [comment]
The same issue.
Just run the exe, the CPU usage is about 25%-26%.

**Comment by blueminder** [comment]
A few folks have reported similar. I believe it has to do with the recent frame pacing optimizations, but generally the frame pacing is forced by another thread pumping the brakes on render so that input timing is correct. More details on implementation details can be found in this post:

https://www.patreon.com/posts/fixed-video-68867417

I'm definitely looking into further optimizations. I just wanted to have folks try it out in its current state to evaluate performance improvements in the general public. In spite of the greater CPU usage, it seems to make things smoother. I would like to cut it down though.

**Comment by WAZAAAAA0** [comment]
can't you like add a sleep(1) or sleep(0.5) to the spinlock loop to ease the pain?

**Comment by leoxxx** [comment]
0.5.4's CPU usage is 2%.

**Comment by blueminder** [comment]
This should be solved in 0.5.4. Let me know when you try it out.

**Comment by WAZAAAAA0** [comment]
0.5.4 helped reduce the CPU waste a bit, but I'm not convinced yet. CPU usage is now down to 9% for me, but 0.4.57 was 2%

Looking at the relevant code in mainui.cpp <https://github.com/blueminder/flycast-dojo/commit/0411f7599df09547299d8651e6ade9e9348ede63>, if I'm reading it right, the timeBeginPeriod and timeEndPeriod (calls used to request Windows accurate timers for accurate Sleeps) are inside a while loop. There's no reason for that to be the case for 2 reasons:
1. somehow 0.4.57 was already requesting the global timer resolution of 1ms for me immediately upon launching Flycast.exe (this can be checked using [OpenTimerResolution](https://github.com/tornix0/opentimerresolution), the only good tool for the job because it's the only one that updates the current timer continuously btw)
2. no need to request timeBeginPeriod multiple times at all, once is enough, it's a global change

And personally I wouldn't even bother calling timeEndPeriod at all, because closing the program that requested a higher resolution timer (Flycast.exe) already resets it back to the norm

**Comment by blueminder** [comment]
Thanks for the tool link, that's pretty handy.

I was actually able to make the CPU usage even lower by increasing the sleep time on both threads, but this came at the cost of frame rate consistency since there's little guarantee that a thread can wake up after sleep. Since frame rate consistency is what I was optimizing for in the first place, I kept my initial changes. (This was a big reason I went a bit overboard with timer resolution calls. I'll be sure to take them out of the while loop, like you say.)

I plan on further optimizing fixed frequency in something other than a spinlock eventually, so I imagine this won't be the last of the optimizations. All that said, the slightly increased CPU usage from 0.4.57 does actually serve a purpose more than making your CPU churn.

**Comment by leoxxx** [comment]
@blueminder 

> Toggle to turn off Optimizations

Where is the option?

**Comment by blueminder** [comment]
>  @blueminder 
> 
> > Toggle to turn off Optimizations
> 
> Where is the option?

Directly under the Fixed Frequency toggle

**Comment by blueminder** [comment]
> @blueminder
> Where is the option?

Directly under the Fixed Frequency toggle in the Video settings.

![image](https://user-images.githubusercontent.com/504581/193221765-145149a5-4239-41a5-abc8-b2b3fac41831.png)

**Comment by WAZAAAAA0** [comment]
love the idea of making it optional, and since it's a thing now, mayyybe make the low CPU option of the two more similar to 0.4.57 CPU wise (raise the sleeps?)

recap
```
0.4.57 =  2%
0.5.1  = 25%
0.5.4  =  9%
0.5.5  = 13% (Fixed Frequency CPU Optimizations ON, default)
0.5.5  = 25% (Fixed Frequency CPU Optimizations OFF)
```

**Comment by blueminder** [comment]
> love the idea of making it optional, and since it's a thing now, mayyybe make the low CPU option of the two more similar to 0.4.57 CPU wise (raise the sleeps?)

0.4.57 just didn't have Fixed Frequency at all. You can disable it outright and enable Audio Sync if you want it to match that version.

**Comment by WAZAAAAA0** [comment]
<details>
  <summary>(old post)</summary>
  
  > You can disable the feature outright

  Oh so it was optional from the beginning (`Video->Advanced->Display->Fixed Frequency: Disabled`). That knowledge would've been enough to close the issue for me, but at least we tackled the superflous Windows Resolution Timer code and you added that optimization in the meanwhile 👌

  It should be probably mentioned somewhere that toggling Fixed Frequency ON and OFF requires a program reboot, that's why I didn't notice it the first time around, I had to restart Flycast to really apply the change (the CPU reflected this)
  
</details>

# **OPTIMIZED FLYCAST DOJO OPTIONS FOR DOA2LE**
`- Settings -> Audio -> Audio Frame Sync: OFF`
Makes frame times more consistent during gameplay (can verify this using the MSI Afterburner Frametime graph with decimal precision enabled). If you need to play Story Mode set this to ON so cutscenes don't run at double speed (since they run at 30 FPS).

`- Settings -> Advanced -> Multi-threaded emulation: ON`
Various reports of performance improving with this.

`- Settings -> Video -> Advanced -> Display -> Fixed Frequency: Disabled`
Disable the spinlock described in this thread, saves 1 full CPU core from being wasted.

`- Settings -> Video -> Graphics API: Vulkan`
Use whatever graphic API ensures the bypassing of the desktop composition (DWM) to keep input lag low by using the proper "presentation model" (aka exclusive fullscreen) on your machine. For me it's Vulkan.

`- Settings -> Video -> Advanced -> Display -> VSync: OFF`
With this last option disabled, there's nothing in place limiting the FPS. These 3 options can cap the game at 60 FPS if used, but they're flawed:
*Audio Frame Sync* has inconsistent frametimes.
*Fixed Frequency* has huge CPU waste.
*VSync* has noticeable input lag.
...thus the game will now run at uncapped super fast FPS speed, and we don't want that. So you'll have to...

`- cap your framerate to 60 somehow`
You'll need an external method for this. If you're lazy, you can just ignore the previous instruction and turn VSync ON. Otherwise the best method for me as someone without a fancy FreeSync/G-Sync monitor is to enable the *MSI Afterburner RivaTuner Scanline-Sync* feature which magically defeats screen tearing with no input lag penalty while running the game at a perfect stable 60 FPS. Otherwise you can cap flycast.exe's FPS to 60 with NVIDIA or AMD's control panel, your choice.

`- Alt+Enter to play fullscreen`
So that the forced V-Sync (input lag) caused by playing windowed games known as DWM aka Aero aka desktop composition doesn't happen.

## OPTIONAL SETTINGS
`- Settings -> Video -> Show FPS Counter ON`
`- Settings -> Netplay -> Show Network Statistics Overlay ON`
`- Settings -> Netplay -> Player Name -> type your nickname` (better for spectators, and better than having every replay file named just "Player")

Unrelated to performance but they'll make testing easier. When you're done, remember to restart Flycast to apply the settings.

**Comment by leoxxx** [comment]
@blueminder 
I found ngbc will lag and sound broken when "Fixed Frequency CPU Optimizations" on. KYO 236236+KICK, the sound will lag and sound broken. If off the option, it's O.K. But the CPU's useage is too high, more than 50% (for all game). On it , the CPU usage is about 3-12%. In flycast, the CPU's usage is about 11%-22% when running game. The game is O.K.
Test dojo version: 0.5.8
My CPU: I5 3470
Can you optimize it?
