### ISSUE TITLE
Stuck at "Starting Network..."

### ISSUE THREAD

**Issue by ktg5** [blueminder/flycast-dojo#32]
Platform / OS / Hardware:
Windows 11
i5-12600k
RTX 3060

GitHub hash: flycast-dojo-0.5.5 & 0.5.6

**_Description of the Issue_**
When I try to load up into a game with NetPlay (over the internet or locally), both clients get stuck on "Starting Network..."; "Waiting for opponent to select delay."

**_Debugging Steps Tested_**
  * Since I'm doing this locally, I don't need to open up ports.
  * Disabled Windows Firewall.
  * Tried on both v0.5.5 & v0.5.6.
  * Games tried: _Ikaruga_, _Marvel Vs. Capcom 2_ (both Dreamcast & NAOMI versions).
  * As mentioned above, tested both locally and over the internet with a friend (which also tried to do it locally but didn't work).

I haven't tried earlier versions yet but if needed I can.

**_Logs Gathered_**
https://gist.github.com/ktg5/891acceb24a6985ec426b995cbd63eeb
I ran two instances of Flycast so the log is a bit missy.

**_Screenshots_**
![image](https://user-images.githubusercontent.com/42522603/194740505-a463a148-d90d-4973-b8bf-a6ef32d3bcba.png)

**Comment by blueminder** [comment]
If you're running on the same machine, did you disable Match Codes?

**Comment by ktg5** [comment]
I was using Match Codes and I tried using Direct IP, which sadly didn't work. I even got to open up the ports mentioned in the FAQ, but that didn't work either.

**Comment by blueminder** [comment]
Did you try connecting to yourself with Direct IP enabled? You should be able to start a game with two instances locally if you leave it blank. I do this for testing all the time.

**Comment by ktg5** [comment]
Sorry for the long delay -- I totally forgot I made this and I should have put notifications on here.
I actually got it to work with Direct IP without having to put in an IP -- guess I wasn't setting it up properly.
![image](https://user-images.githubusercontent.com/42522603/197366582-6d128e73-2408-403f-ad25-afdec002c4eb.png)
But that still makes me question as to why Match Codes doesn't work?
