### ISSUE TITLE
Flycast-dojo does not work in Ubuntu 22.04

### ISSUE THREAD

**Issue by mmalone-tongal** [blueminder/flycast-dojo#33]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Ubuntu 22.04

Github hash: flycast-dojo-0.5.5

Hardware:  64GB DDR4 RAM, Ryzen 7 16 core CPU, Nvidia 960 GTX

**_Description of the Issue_**

Unfortunately, this app relies on `libzip5` and currently, there is no way to install it on Ubuntu 22.04

**_Debugging Steps Tested_**
N/A 
Attempting to install libzip5 results in the following error:
`E: Unable to locate package libzip5`

  * I tried searching for a manual way to install the package but found nothing.

**_Logs Gathered_**
`./flycast.elf: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory`

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by mmalone-tongal** [comment]
I manually installed the dependencies from some .deb files but like the previous version of Ubuntu, hopefully they add them back to the `apt` package manager

**Comment by blueminder** [comment]
You can either use the Fightcade Flatpak or find Ubuntu backport repositories for now.

I do plan on updating the Ubuntu version on the build instance, it's just that most folks have not caught up up to now.
