### ISSUE TITLE
You Confused?

### ISSUE THREAD

**Issue by Jeju79** [blueminder/flycast-dojo#34]
Add to The King of Fighters: Dream Match 1999
I don't think you upload The King of Fighters: Dream Match 1999 because you think it's the same thing as playing kof'99 evo, but it's a different game. It is a dreamcast game based on 1998.

**Comment by blueminder** [comment]
I think you're the one that's confised. I have no clue if you're referring to a netplay savestate, Fightcade lobby, or what, but this is the wrong place to ash for any of those. This is the issues page for the emulator itself.

Closed.
