### ISSUE TITLE
Flycast using too much ram on Arch Linux / memory leakage

### ISSUE THREAD

**Issue by lunelovehearn** [blueminder/flycast-dojo#36]
**Platform / OS / Hardware:** Arch Linux, kernel 6.0.12-zen, with KDE Plasma 5.26.x

Hardware: AMD Ryzen 3xxx with Radeon Vega GPU, !6 GB RAM
![2022-12-13_20-34](https://user-images.githubusercontent.com/84490883/207468182-d1fdb965-ff1e-4056-b830-5f3189edf032.png)

**_Description of the Issue_**
when playing online matches and exiting, flycast freezes or stays on background, using from 1G up to 5GB RAM, making me force close it/kill the process to release the memory. it also happens when ingame online on the flatpak version, which is the solely version I run. on offline matches or training there's no memory leakage so far but it does stay on the backgroud after closing the main window. 
**Note: the ram usage begins at 200mb and keeps rising the longer you play on flycast, hitting over 3GB RAM usage.**

**_Debugging Steps Tested_**

  * open flycast from within fightcade flatpak then challenge someone and play for 30 mins
  * finish the match, flycast will remain in memory on the background eating RAM.
  * user has to open system monitor to kill flicast.elf before it eats almost all the RAM

**_Logs Gathered_**

```
00:00:960 sdl/sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:975 rend/vulkan/vulkan_context.cpp:234 N[RENDERER]: Vulkan API 1.1. Device AMD RADV RAVEN
00:01:001 rend/vulkan/vulkan_context.h:261 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:01:008 rend/gui.cpp:344 N[RENDERER]: Screen DPI is 142, size 1920 x 988. Scaling by 1.06
00:01:056 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:01:163 rend/vulkan/vulkan_context.h:261 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:01:291 rend/vulkan/vulkan_context.h:261 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:10:536 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:10:553 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 0x7fd32bff0000 RAM(16 MB) 0x7fd3b7ff0000 VRAM64(8 MB) 0x7fd3afff0000 ARAM(2 MB) 0x7fd3ac7f0000
00:10:559 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:10:585 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 0x7fd32bff0000 RAM(32 MB) 0x7fd3b7ff0000 VRAM64(16 MB) 0x7fd3afff0000 ARAM(8 MB) 0x7fd3ac7f0000
00:11:490 hw/naomi/naomi_cart.cpp:579 N[NAOMI]: NAOMI GAME ID [MARVEL VS CAPCOM2  JAPAN] region ff players 2 vertical 1
00:11:490 emulator.cpp:235 N[BOOT]: Game ID is [MARVEL VS CAPCOM2  JAPAN]
00:11:497 hw/naomi/naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:00:675 sdl/sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:703 rend/vulkan/vulkan_context.cpp:234 N[RENDERER]: Vulkan API 1.1. Device AMD RADV RAVEN
00:00:747 rend/vulkan/vulkan_context.h:261 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:748 rend/gui.cpp:344 N[RENDERER]: Screen DPI is 142, size 1920 x 988. Scaling by 1.06
00:00:807 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:01:163 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:01:182 rend/vulkan/vulkan_context.h:261 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:01:184 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 0x7fbdb7ff0000 RAM(16 MB) 0x7fbe43ff0000 VRAM64(8 MB) 0x7fbe3bff0000 ARAM(2 MB) 0x7fbe387f0000
00:01:193 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:01:229 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 0x7fbdb7ff0000 RAM(32 MB) 0x7fbe43ff0000 VRAM64(16 MB) 0x7fbe3bff0000 ARAM(8 MB) 0x7fbe387f0000
00:02:945 hw/naomi/naomi_cart.cpp:579 N[NAOMI]: NAOMI GAME ID [MARVEL VS CAPCOM2  JAPAN] region ff players 2 vertical 1
00:02:945 emulator.cpp:235 N[BOOT]: Game ID is [MARVEL VS CAPCOM2  JAPAN]
00:02:966 hw/naomi/naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:06:984 network/ggpo.cpp:510 N[NETWORK]: GGPO: Using 0 full analog axes
21:14:713 linux/common.cpp:70 E[COMMON]: SIGSEGV @ 0x7fbefd61a689 -> 0x7fbe41ff0000 was not in vram, dynacode:0

```

**_Screenshots_**
attached flycast version and a system monitor shot. will add more soon.

![2022-12-13_18-34](https://user-images.githubusercontent.com/84490883/207451092-303a7675-e737-4cf5-869e-0a8f9a98dc23.png)
![2022-12-13_18-40](https://user-images.githubusercontent.com/84490883/207451111-2be588b1-a6a4-44d2-b570-fcfa30d15b2c.png)
![log](https://user-images.githubusercontent.com/84490883/207467251-008ac5ee-b0fa-44cb-b3b6-8b245b697201.png)

**Comment by kazuhiroshigeru** [comment]
pobega said that there's a pending pull on main FC repo, and this issue is pending of being solved, as talked on the FC flycast channel on discord.

**Comment by Pobega** [comment]
> pobega said that there's a pending pull on main FC repo, and this issue is pending of being solved, as talked on the FC flycast channel on discord.

For clarity the pending pull is just for log writing support, not to resolve any sort of memory leak issues.

https://github.com/flathub/com.fightcade.Fightcade/pull/108
