### ISSUE TITLE
Why does Flycast dojo doesn't work on android TV?

### ISSUE THREAD

**Issue by mrmagicm93** [blueminder/flycast-dojo#37]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Android V

Github hash: 

Hardware: Sony TV KD-55XE8596 Bravia

**_Description of the Issue_** 
Cannot open file

Add a short, concise description of the issue here
Cannot open file, kind of right issue
```
I don't know where to take logs....

Can someone tell me?

**Comment by blueminder** [comment]
Officially, there is no Android release yet.
