### ISSUE TITLE
upgrade libzip requirements to current version (or help with building on linux)

### ISSUE THREAD

**Issue by teletrail** [blueminder/flycast-dojo#43]
is it possible to upgrade the libzip requirement to the current version? my package manager does not have an older version to install, I have all other required packages installed. 

or is it possible to build this on linux (gentoo current) I attempted to run "cmake .." however there were errors during configure.

thanks I would like to test this app a lot!

**Comment by blueminder** [comment]
Unsure if this is relevant on the newest versions, but since I distribute this as an AppImage, the library matches the Ubuntu build it's generated on. You can look at the GitHub Workflow to see how it is compiled, as well as its target runner image.
