### ISSUE TITLE
CVS2 Dreamcast Always with Training options there

### ISSUE THREAD

**Issue by ez2torta** [blueminder/flycast-dojo#44]
Platform / OS / Hardware: 
SteamOS
Github hash: 
Flycast Dojo 6.3
Hardware: 
SteamDeck

**_Description of the Issue_**

I tried the Dreamcast ISO of CvS2 on OFFLINE and it ran well until i got to fight anyone and all this training windows with info were there, no option for them to disable, just like minimizing them while still being on the screen.

Any suggestions? i thought that they were only going to be there in TRAIN mode

**_Screenshots_**

![image](https://github.com/blueminder/flycast-dojo/assets/5553942/2b31998f-f258-4892-a15b-f41f2197ad05)

**Comment by blueminder** [comment]
Just fixed this bug. Should be in a prerelease hitting tomorrow. Will close the ticket once it's out.

**Comment by blueminder** [comment]
Fixed in 6.6

**Comment by ez2torta** [comment]
Thank you Enrique!
