### ISSUE TITLE
project justice flycast constant crashes

### ISSUE THREAD

**Issue by crowspaceboy** [blueminder/flycast-dojo#45]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
fightcade / windows / PC
flycast version: dojo-0.5.8
Github hash: 

Hardware: 

**_Description of the Issue_**

I am getting constant crashes in Project Justice. The game itself runs fine, probably the best running flycast game for me. But it intermittently crashes, and for the past few weeks, it's been crashing a lot, and I have no idea why. I'm not sure what info to provide—it just hangs and then eventually closes. It does not matter how good or bad the connection is: the most recent crash was a Austin TX to Dallas TX 16 ping connection, one that used to perform flawlessly a few flycast builds ago but now crashes pretty regularly after like 10-15 minutes or so

**_Debugging Steps Tested_**

happens when playing with multiple users
tried deleting savestate -> redownloading, issue persists

**_Logs Gathered_**

```

i would provide logs if I had any idea how to get them.
```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blueminder** [comment]
> i would provide logs if I had any idea how to get them.

The documentation has a page on collecting logs for troubleshooting here:
https://dojo-project.gitbook.io/flycast-dojo/overview/collecting-logs-for-troubleshooting

**Comment by blueminder** [comment]
> But it intermittently crashes, and for the past few weeks, it's been crashing a lot, and I have no idea why. I'm not sure what info to provide—it just hangs and then eventually closes.

There have been no changes to the version of Flycast Dojo bundled with Fightcade that would have only happened in the last few weeks. It sounds like a network issue to me. this can happen either on your end or your opponent. I would check to see if there were any changes to your own network configuration or router during that time.

>  the most recent crash was a Austin TX to Dallas TX 16 ping connection, one that used to perform flawlessly a few flycast builds ago but now crashes pretty regularly after like 10-15 minutes or so

What builds? It's best to be specific. the version with Fightcade hasn't been changed since last December.

You may also want to try using the latest pre-release with other willing opponents that have the same. If the issue persists during that time, then it is more likely to be a network issue than not.

**Comment by crowspaceboy** [comment]
Just had two more crashes in these replays with a player local to me:
https://replay.fightcade.com/flycast/flycast_pjustic/1700895131229-2595 after 8 minutes
https://replay.fightcade.com/flycast/flycast_pjustic/1700895131229-2595 after 25 minutes. (this one actually went far longer than any crash i've had in PJ, not sure why this was different.)

It continues to only be PJ. Did a hour long SC1 session without any crashes the night before:
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1700805396886-3492

And now!! I have logs. I.. do not know how to read these, but I hope something here is useful? If this didn't capture anything that looks like an issue, I guess my next step is to do that debug view thing.

00:00:074 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:333 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:087 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:309 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:058 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:252 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:01:474 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:01:486 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff451ad0000 RAM(16 MB) 00007ff45dad0000 VRAM64(8 MB) 00007ff455ad0000 ARAM(2 MB) 00007ff471ad0000
00:01:499 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:01:511 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff451ad0000 RAM(16 MB) 00007ff45dad0000 VRAM64(8 MB) 00007ff455ad0000 ARAM(2 MB) 00007ff471ad0000
00:01:570 emulator.cpp:57 N[BOOT]: Game ID is [T1401N]
00:01:729 nullDC.cpp:267 W[SAVESTATE]: Failed to load state - could not open D:\Users\Crow\Documents\Fightcade\emulator\flycast\data\Soulcalibur (USA)_1.state for reading
00:00:061 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:231 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:305 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:319 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4c5a60000 RAM(16 MB) 00007ff4d1a60000 VRAM64(8 MB) 00007ff4c9a60000 ARAM(2 MB) 00007ff4e5a60000
00:00:329 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:343 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4c5a60000 RAM(16 MB) 00007ff4d1a60000 VRAM64(8 MB) 00007ff4c9a60000 ARAM(2 MB) 00007ff4e5a60000
00:00:391 emulator.cpp:57 N[BOOT]: Game ID is [T1401N]
00:00:400 emulator.cpp:550 N[BOOT]: Did not load BIOS, using reios
00:00:056 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:227 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:298 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:309 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff3f7f90000 RAM(16 MB) 00007ff403f90000 VRAM64(8 MB) 00007ff3fbf90000 ARAM(2 MB) 00007ff417f90000
00:00:318 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:330 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff3f7f90000 RAM(16 MB) 00007ff403f90000 VRAM64(8 MB) 00007ff3fbf90000 ARAM(2 MB) 00007ff417f90000
00:00:359 emulator.cpp:57 N[BOOT]: Game ID is [T1401N]
00:00:367 emulator.cpp:550 N[BOOT]: Did not load BIOS, using reios
00:00:055 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:230 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:304 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:316 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4b52b0000 RAM(16 MB) 00007ff4c12b0000 VRAM64(8 MB) 00007ff4b92b0000 ARAM(2 MB) 00007ff4d52b0000
00:00:325 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:337 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4b52b0000 RAM(16 MB) 00007ff4c12b0000 VRAM64(8 MB) 00007ff4b92b0000 ARAM(2 MB) 00007ff4d52b0000
00:00:366 emulator.cpp:57 N[BOOT]: Game ID is [T1401N]
00:00:374 emulator.cpp:550 N[BOOT]: Did not load BIOS, using reios
00:00:054 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:219 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:04:108 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:04:119 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4782b0000 RAM(16 MB) 00007ff4842b0000 VRAM64(8 MB) 00007ff47c2b0000 ARAM(2 MB) 00007ff4982b0000
00:04:127 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:04:139 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff4782b0000 RAM(16 MB) 00007ff4842b0000 VRAM64(8 MB) 00007ff47c2b0000 ARAM(2 MB) 00007ff4982b0000
00:04:168 emulator.cpp:57 N[BOOT]: Game ID is [T1401N]
00:04:176 emulator.cpp:550 N[BOOT]: Did not load BIOS, using reios
00:00:072 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:372 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:500 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:511 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff456df0000 RAM(16 MB) 00007ff462df0000 VRAM64(8 MB) 00007ff45adf0000 ARAM(2 MB) 00007ff476df0000
00:00:521 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:549 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff456df0000 RAM(32 MB) 00007ff462df0000 VRAM64(16 MB) 00007ff45adf0000 ARAM(8 MB) 00007ff476df0000
00:02:381 hw\naomi\naomi_cart.cpp:582 N[NAOMI]: NAOMI GAME ID [MOERO JUSTICE GAKUEN  JAPAN] region ff players 2 vertical 1
00:02:381 emulator.cpp:268 N[BOOT]: Game ID is [MOERO JUSTICE GAKUEN  JAPAN]
00:02:447 hw\naomi\naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:02:447 emulator.cpp:268 N[BOOT]: Game ID is [MOERO JUSTICE GAKUEN  JAPAN]
00:10:477 network\ggpo.cpp:510 N[NETWORK]: GGPO: Using 0 full analog axes
00:00:062 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:235 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:304 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:317 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff412b70000 RAM(16 MB) 00007ff41eb70000 VRAM64(8 MB) 00007ff416b70000 ARAM(2 MB) 00007ff432b70000
00:00:326 hw\mem\_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:00:352 hw\mem\_vmem.cpp:589 N[VMEM]: BASE 00007ff412b70000 RAM(32 MB) 00007ff41eb70000 VRAM64(16 MB) 00007ff416b70000 ARAM(8 MB) 00007ff432b70000
00:01:805 hw\naomi\naomi_cart.cpp:582 N[NAOMI]: NAOMI GAME ID [MOERO JUSTICE GAKUEN  JAPAN] region ff players 2 vertical 1
00:01:805 emulator.cpp:268 N[BOOT]: Game ID is [MOERO JUSTICE GAKUEN  JAPAN]
00:01:817 hw\naomi\naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:01:817 emulator.cpp:268 N[BOOT]: Game ID is [MOERO JUSTICE GAKUEN  JAPAN]
00:12:146 network\ggpo.cpp:510 N[NETWORK]: GGPO: Using 0 full analog axes
00:00:058 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:223 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00
00:00:066 sdl\sdl.cpp:581 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:264 rend\gui.cpp:349 N[RENDERER]: Screen DPI is 96, size 1004 x 724. Scaling by 1.00

**Comment by blueminder** [comment]
Old version. Feel free to reopen if this occurs in the future.
