### ISSUE TITLE
Virtual-On: Oratorio Tangram USA CHD

### ISSUE THREAD

**Issue by ChexGuy** [blueminder/flycast-dojo#46]
flycast_roms.json lists the following CHD for Virtual-On: Oratorio Tangram:
`Cyber Troopers - Virtual-On - Oratorio Tangram (USA).chd`
`md5: 389a4c7c8808f769659b10d8ceaa5320`
This particular ROM has audio issues, including a heavy delay before a track starts in a menu or match.

A CHD without said audio issues is called:
`Cyber Troopers - Virtual On - Oratorio Tangram v1.000 (2000)(Activision)(US)[!].chd`
`md5: 44083e32229f1f87421aac763485af40`

**Comment by blueminder** [comment]
Fixed in the latest prerelease. Thanks for the heads up.
