### ISSUE TITLE
Special characters in folder path = can't boot game through command line

### ISSUE THREAD

**Issue by WAZAAAAA0** [blueminder/flycast-dojo#47]
Trying to launch a game that's in a folder path with special symbols in it directly through command line parameters will fail.

Tested on Win10 and Win11.

Affects both the old `dojo-0.5.8 284946ba5 (Fightcade edition)` and the new `dojo-6.11 ec8590fc5`.

COMMAND LINE EXAMPLES:
`C:\ÅÅÅ\flycast-dojo-6.11\flycast.exe -config dojo:GameEntry=dc_doa2_le` fails and quits
`C:\BBB\flycast-dojo-6.11\flycast.exe -config dojo:GameEntry=dc_doa2_le` game starts successfully

**Comment by blueminder** [comment]
I just put in a fix for Unicode file path handling for JSON and it's running through the CI now. I just tested it locally. As soon as the build is finished, I'll shoot out the next prerelease.

https://github.com/blueminder/flycast-dojo/commit/07c87ce43dafa4611e2157b525851b83ac24b623

**Comment by blueminder** [comment]
Fixed in [Dojo 6.12](https://github.com/blueminder/flycast-dojo/releases/tag/dojo-6.12)
