### ISSUE TITLE
Macro commands block directional input (i.e. cannot move around with zangief's 3xpunch/3xkick special move)

### ISSUE THREAD

**Issue by mtsh1000** [blueminder/flycast-dojo#5]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blueminder** [comment]
Controller mapping is currently in the middle of being overhauled on upstream Flycast. As soon as that is finished, I will be overhauling how macros work as well. This is definitely on my radar.

I temporarily disabled the feature for now to not mess up player expectations during game sessions. Thanks for bringing this up.

**Comment by mtsh1000** [comment]
I tested this further and it seems that it happens only when 3xP/K is mapped to an analog trigger and is combined with d-pad direction. Using normal buttons as 3xP/K or using analog stick with analog 3xP/K works fine. Anyways keep up the great work:)

**Comment by blueminder** [comment]
Can you check this again on the latest test build 9A? With the controller mapping overhaul, I also changed how macros work. I will close this once I have confirmation of it working.

**Comment by mtsh1000** [comment]
Just tested v9A - it's fixed:)
