### ISSUE TITLE
Fightcade Flycast not saving Controller Mappings

### ISSUE THREAD

**Issue by ez2torta** [blueminder/flycast-dojo#52]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 11

Github hash: 
(Latest Fightcade Version?)

Hardware: 
- HP Omen Laptop
- Intel Core I7 9th Gen
- Nvidia RTX 2060
- 16GB RAM
- 512GB SSD

**_Description of the Issue_**

I updated Fightcade a few weeks ago and had a few CvS2 Matches without problem :)

Last week i tried to play again but the controllers were not mapped. Then i used TestGame function to play against the CPU and map the controllers.. Then closed Flycast Dojo and when i got to a match the controller was not mapped correctly again.

What can i do? should i reinstall Fightcade into another folder? I wish Linux worked on that machine but sadly i've had tons of incompatibility issues

**_Debugging Steps Tested_**

* Haven't actually reinstalled fightcade, just used its updater
* i think i have had this problem on windows before, but don't know how to actually fix this 

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

* Gonna upload a video during this week

**Comment by ez2torta** [comment]
We had another Fightcade Update today and the button check worked flawlessly.. i don't know what happened but well, it did not happen hahaha

**Comment by blueminder** [comment]
Glad to hear it works again! I'm unsure what happens with the Fightcade update mechanism, but a fresh install has typically works when it comes up after an update occurs. Thanks for letting me know.
